# Generated by Django 4.2.6 on 2023-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.CharField(blank=True, max_length=15, verbose_name="해시태그"),
        ),
        migrations.AlterField(
            model_name="post",
            name="like_count",
            field=models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
        ),
        migrations.AlterField(
            model_name="post",
            name="share_count",
            field=models.PositiveIntegerField(default=0, verbose_name="공유 수"),
        ),
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회 수"),
        ),
    ]
